Repository googleapis/java-binary-authorization, pull requests merged in 2021-09, with the labels that each got.

#77 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: binaryauthorization

#85 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: automerge, cla: yes, api: binaryauthorization

#93 Update .repo-metadata.json
  .github/CODEOWNERS
  .repo-metadata.json
Labels: automerge, cla: yes, api: binaryauthorization

#96 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: binaryauthorization
