Repository googleapis/java-binary-authorization, pull requests merged in 2022-01, with the labels that each got.

#140 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: binaryauthorization, owlbot:ignore

#145 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: binaryauthorization, owlbot:ignore

#147 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: automerge, api: binaryauthorization

#144 chore: Update .repo-metadata.json
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: binaryauthorization
